version: "3"
services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      #- MONGODB_USERNAME=root
      #- MONGODB_PASSWORD=SN5GWkQzuie7dNZe
      #- MONGODB_DATABASE=Cluster0
      - MONGODB_CONNECTION_STRING=mongodb://mongo/placebook
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
      - ./backend/__tests__:/app/__tests__
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
