const User = require('./user')
const Restaurant = require('./restaurant')
const Order = require('./order')

const ayse = new User('ayse')
const samis = new Restaurant('samis')

ayse.likeRestaurant(samis)
samis.createMenu('pizza')
samis.createMenu('beverages')
samis.menus[0].addProduct('margaritta', 10)
samis.menus[0].addProduct('salami', 15)
samis.menus[0].addProduct('vegetarish', 12)
samis.menus[1].addProduct('Coca cola', 2)
samis.menus[1].addProduct('Fanta', 2)
samis.menus[1].addProduct('Sprite', 2.3)
samis.menus[1].addProduct('Ice tea', 1.8)

const order1 = new Order()
// console.log(samis.menus[0])

order1.addProduct(samis.menus[0].productNames[0], 1)
order1.addProduct(samis.menus[1].productNames[0], 1)
order1.calculateAmount()
console.log(order1)
ayse.createOrder()

console.log(samis.profile)
console.log(samis.menus[0].menuInfo)
console.log('\n')
console.log(samis.menus[1].menuInfo)
